replicaCount: 3

image:
  repository: qwen-agent
  tag: v1.0.1
  pullPolicy: Always

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75