name: CI/CD with Eval Gating

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Deps
        run: pip install -r requirements.txt
      - name: Test & Eval
        run: |
          pytest tests/
          python scripts/langchain_eval_runner.py
      - name: Helm Deploy
        if: success()
        run: |
          helm upgrade --install qwen-agent ./infra/helm --values infra/helm/values.yaml
